# txing weather Matter app identity and data model.
CONFIG_CHIP_PROJECT_CONFIG="src/chip_project_config.h"
CONFIG_CHIP_DEVICE_PRODUCT_NAME="txing Weather"
CONFIG_CHIP_DEVICE_PRODUCT_ID=32781
CONFIG_CHIP_DEVICE_TYPE=770
CONFIG_NCS_SAMPLE_MATTER_ZAP_FILE_PATH="${APPLICATION_CONFIG_DIR}/src/default_zap/weather-station.zap"

CONFIG_BT_DEVICE_NAME="TxingWeather"
