// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: txing/cyberbrick/hardware/v1/cyberbrick_hardware.proto

package hardwarev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CyberbrickHardware_GetStatus_FullMethodName     = "/txing.cyberbrick.hardware.v1.CyberbrickHardware/GetStatus"
	CyberbrickHardware_ApplyVelocity_FullMethodName = "/txing.cyberbrick.hardware.v1.CyberbrickHardware/ApplyVelocity"
	CyberbrickHardware_Stop_FullMethodName          = "/txing.cyberbrick.hardware.v1.CyberbrickHardware/Stop"
)

// CyberbrickHardwareClient is the client API for CyberbrickHardware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CyberbrickHardwareClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*HardwareStatus, error)
	ApplyVelocity(ctx context.Context, in *ApplyVelocityRequest, opts ...grpc.CallOption) (*ApplyVelocityResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type cyberbrickHardwareClient struct {
	cc grpc.ClientConnInterface
}

func NewCyberbrickHardwareClient(cc grpc.ClientConnInterface) CyberbrickHardwareClient {
	return &cyberbrickHardwareClient{cc}
}

func (c *cyberbrickHardwareClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*HardwareStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HardwareStatus)
	err := c.cc.Invoke(ctx, CyberbrickHardware_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberbrickHardwareClient) ApplyVelocity(ctx context.Context, in *ApplyVelocityRequest, opts ...grpc.CallOption) (*ApplyVelocityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyVelocityResponse)
	err := c.cc.Invoke(ctx, CyberbrickHardware_ApplyVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberbrickHardwareClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, CyberbrickHardware_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CyberbrickHardwareServer is the server API for CyberbrickHardware service.
// All implementations must embed UnimplementedCyberbrickHardwareServer
// for forward compatibility.
type CyberbrickHardwareServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*HardwareStatus, error)
	ApplyVelocity(context.Context, *ApplyVelocityRequest) (*ApplyVelocityResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedCyberbrickHardwareServer()
}

// UnimplementedCyberbrickHardwareServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCyberbrickHardwareServer struct{}

func (UnimplementedCyberbrickHardwareServer) GetStatus(context.Context, *GetStatusRequest) (*HardwareStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCyberbrickHardwareServer) ApplyVelocity(context.Context, *ApplyVelocityRequest) (*ApplyVelocityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVelocity not implemented")
}
func (UnimplementedCyberbrickHardwareServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCyberbrickHardwareServer) mustEmbedUnimplementedCyberbrickHardwareServer() {}
func (UnimplementedCyberbrickHardwareServer) testEmbeddedByValue()                            {}

// UnsafeCyberbrickHardwareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CyberbrickHardwareServer will
// result in compilation errors.
type UnsafeCyberbrickHardwareServer interface {
	mustEmbedUnimplementedCyberbrickHardwareServer()
}

func RegisterCyberbrickHardwareServer(s grpc.ServiceRegistrar, srv CyberbrickHardwareServer) {
	// If the following call pancis, it indicates UnimplementedCyberbrickHardwareServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CyberbrickHardware_ServiceDesc, srv)
}

func _CyberbrickHardware_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberbrickHardwareServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberbrickHardware_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberbrickHardwareServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberbrickHardware_ApplyVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberbrickHardwareServer).ApplyVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberbrickHardware_ApplyVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberbrickHardwareServer).ApplyVelocity(ctx, req.(*ApplyVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberbrickHardware_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberbrickHardwareServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberbrickHardware_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberbrickHardwareServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CyberbrickHardware_ServiceDesc is the grpc.ServiceDesc for CyberbrickHardware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CyberbrickHardware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "txing.cyberbrick.hardware.v1.CyberbrickHardware",
	HandlerType: (*CyberbrickHardwareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _CyberbrickHardware_GetStatus_Handler,
		},
		{
			MethodName: "ApplyVelocity",
			Handler:    _CyberbrickHardware_ApplyVelocity_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CyberbrickHardware_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txing/cyberbrick/hardware/v1/cyberbrick_hardware.proto",
}
