# Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_BM_UARTE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_RTT_MODE_DROP=y
CONFIG_LOG_BACKEND_RTT_MESSAGE_SIZE=256
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096

# SoftDevice S115
CONFIG_SOFTDEVICE=y
CONFIG_NRF_SDH_BLE_VS_UUID_COUNT=1

# SoftDevice BLE initialization uses PSA RNG.
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
CONFIG_PSA_WANT_GENERATE_RANDOM=y

# Advertising data encoder.
CONFIG_BLE_ADV=y

# Grove BME280 over XIAO I2C connector.
CONFIG_NRFX_TWIM=y

CONFIG_TXING_WEATHER_BM_LOG_LEVEL_INF=y
