set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
set quiet := true

time_dir := source_directory()

@test:
    just --justfile "{{time_dir}}/lambda/justfile" test

@default:
    @just --list

mod lambda 'lambda/justfile'
