// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: txing/unit/hardware/v1/unit_hardware.proto

package hardwarev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnitHardware_GetStatus_FullMethodName     = "/txing.unit.hardware.v1.UnitHardware/GetStatus"
	UnitHardware_ApplyVelocity_FullMethodName = "/txing.unit.hardware.v1.UnitHardware/ApplyVelocity"
	UnitHardware_Stop_FullMethodName          = "/txing.unit.hardware.v1.UnitHardware/Stop"
)

// UnitHardwareClient is the client API for UnitHardware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnitHardwareClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*HardwareStatus, error)
	ApplyVelocity(ctx context.Context, in *ApplyVelocityRequest, opts ...grpc.CallOption) (*ApplyVelocityResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type unitHardwareClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitHardwareClient(cc grpc.ClientConnInterface) UnitHardwareClient {
	return &unitHardwareClient{cc}
}

func (c *unitHardwareClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*HardwareStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HardwareStatus)
	err := c.cc.Invoke(ctx, UnitHardware_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitHardwareClient) ApplyVelocity(ctx context.Context, in *ApplyVelocityRequest, opts ...grpc.CallOption) (*ApplyVelocityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyVelocityResponse)
	err := c.cc.Invoke(ctx, UnitHardware_ApplyVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitHardwareClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, UnitHardware_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnitHardwareServer is the server API for UnitHardware service.
// All implementations must embed UnimplementedUnitHardwareServer
// for forward compatibility.
type UnitHardwareServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*HardwareStatus, error)
	ApplyVelocity(context.Context, *ApplyVelocityRequest) (*ApplyVelocityResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedUnitHardwareServer()
}

// UnimplementedUnitHardwareServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnitHardwareServer struct{}

func (UnimplementedUnitHardwareServer) GetStatus(context.Context, *GetStatusRequest) (*HardwareStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedUnitHardwareServer) ApplyVelocity(context.Context, *ApplyVelocityRequest) (*ApplyVelocityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVelocity not implemented")
}
func (UnimplementedUnitHardwareServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedUnitHardwareServer) mustEmbedUnimplementedUnitHardwareServer() {}
func (UnimplementedUnitHardwareServer) testEmbeddedByValue()                      {}

// UnsafeUnitHardwareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnitHardwareServer will
// result in compilation errors.
type UnsafeUnitHardwareServer interface {
	mustEmbedUnimplementedUnitHardwareServer()
}

func RegisterUnitHardwareServer(s grpc.ServiceRegistrar, srv UnitHardwareServer) {
	// If the following call pancis, it indicates UnimplementedUnitHardwareServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnitHardware_ServiceDesc, srv)
}

func _UnitHardware_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitHardwareServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnitHardware_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitHardwareServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitHardware_ApplyVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitHardwareServer).ApplyVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnitHardware_ApplyVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitHardwareServer).ApplyVelocity(ctx, req.(*ApplyVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitHardware_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitHardwareServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnitHardware_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitHardwareServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnitHardware_ServiceDesc is the grpc.ServiceDesc for UnitHardware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnitHardware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "txing.unit.hardware.v1.UnitHardware",
	HandlerType: (*UnitHardwareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _UnitHardware_GetStatus_Handler,
		},
		{
			MethodName: "ApplyVelocity",
			Handler:    _UnitHardware_ApplyVelocity_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _UnitHardware_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txing/unit/hardware/v1/unit_hardware.proto",
}
