// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: txing/unit/hardware/v1/unit_hardware.proto

package hardwarev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareState int32

const (
	HardwareState_HARDWARE_STATE_UNSPECIFIED HardwareState = 0
	HardwareState_STARTING                   HardwareState = 1
	HardwareState_READY                      HardwareState = 2
	HardwareState_DEGRADED                   HardwareState = 3
	HardwareState_ERROR                      HardwareState = 4
	HardwareState_STOPPED                    HardwareState = 5
)

// Enum value maps for HardwareState.
var (
	HardwareState_name = map[int32]string{
		0: "HARDWARE_STATE_UNSPECIFIED",
		1: "STARTING",
		2: "READY",
		3: "DEGRADED",
		4: "ERROR",
		5: "STOPPED",
	}
	HardwareState_value = map[string]int32{
		"HARDWARE_STATE_UNSPECIFIED": 0,
		"STARTING":                   1,
		"READY":                      2,
		"DEGRADED":                   3,
		"ERROR":                      4,
		"STOPPED":                    5,
	}
)

func (x HardwareState) Enum() *HardwareState {
	p := new(HardwareState)
	*p = x
	return p
}

func (x HardwareState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HardwareState) Descriptor() protoreflect.EnumDescriptor {
	return file_txing_unit_hardware_v1_unit_hardware_proto_enumTypes[0].Descriptor()
}

func (HardwareState) Type() protoreflect.EnumType {
	return &file_txing_unit_hardware_v1_unit_hardware_proto_enumTypes[0]
}

func (x HardwareState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HardwareState.Descriptor instead.
func (HardwareState) EnumDescriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{0}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{0}
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Twist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linear        *Vector3               `protobuf:"bytes,1,opt,name=linear,proto3" json:"linear,omitempty"`
	Angular       *Vector3               `protobuf:"bytes,2,opt,name=angular,proto3" json:"angular,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Twist) Reset() {
	*x = Twist{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Twist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Twist) ProtoMessage() {}

func (x *Twist) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Twist.ProtoReflect.Descriptor instead.
func (*Twist) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{2}
}

func (x *Twist) GetLinear() *Vector3 {
	if x != nil {
		return x.Linear
	}
	return nil
}

func (x *Twist) GetAngular() *Vector3 {
	if x != nil {
		return x.Angular
	}
	return nil
}

type MotionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftSpeed     int32                  `protobuf:"varint,1,opt,name=left_speed,json=leftSpeed,proto3" json:"left_speed,omitempty"`
	RightSpeed    int32                  `protobuf:"varint,2,opt,name=right_speed,json=rightSpeed,proto3" json:"right_speed,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotionState) Reset() {
	*x = MotionState{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionState) ProtoMessage() {}

func (x *MotionState) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionState.ProtoReflect.Descriptor instead.
func (*MotionState) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{3}
}

func (x *MotionState) GetLeftSpeed() int32 {
	if x != nil {
		return x.LeftSpeed
	}
	return 0
}

func (x *MotionState) GetRightSpeed() int32 {
	if x != nil {
		return x.RightSpeed
	}
	return 0
}

func (x *MotionState) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type HardwareStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	State                HardwareState          `protobuf:"varint,1,opt,name=state,proto3,enum=txing.unit.hardware.v1.HardwareState" json:"state,omitempty"`
	ActuatorReady        bool                   `protobuf:"varint,2,opt,name=actuator_ready,json=actuatorReady,proto3" json:"actuator_ready,omitempty"`
	LastError            string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Motion               *MotionState           `protobuf:"bytes,4,opt,name=motion,proto3" json:"motion,omitempty"`
	ActiveDeadlineUnixMs *uint64                `protobuf:"varint,5,opt,name=active_deadline_unix_ms,json=activeDeadlineUnixMs,proto3,oneof" json:"active_deadline_unix_ms,omitempty"`
	WorkerVersion        string                 `protobuf:"bytes,6,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HardwareStatus) Reset() {
	*x = HardwareStatus{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareStatus) ProtoMessage() {}

func (x *HardwareStatus) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareStatus.ProtoReflect.Descriptor instead.
func (*HardwareStatus) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{4}
}

func (x *HardwareStatus) GetState() HardwareState {
	if x != nil {
		return x.State
	}
	return HardwareState_HARDWARE_STATE_UNSPECIFIED
}

func (x *HardwareStatus) GetActuatorReady() bool {
	if x != nil {
		return x.ActuatorReady
	}
	return false
}

func (x *HardwareStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *HardwareStatus) GetMotion() *MotionState {
	if x != nil {
		return x.Motion
	}
	return nil
}

func (x *HardwareStatus) GetActiveDeadlineUnixMs() uint64 {
	if x != nil && x.ActiveDeadlineUnixMs != nil {
		return *x.ActiveDeadlineUnixMs
	}
	return 0
}

func (x *HardwareStatus) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

type ApplyVelocityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Twist          *Twist                 `protobuf:"bytes,1,opt,name=twist,proto3" json:"twist,omitempty"`
	DeadlineUnixMs uint64                 `protobuf:"varint,2,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	CommandId      string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyVelocityRequest) Reset() {
	*x = ApplyVelocityRequest{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVelocityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVelocityRequest) ProtoMessage() {}

func (x *ApplyVelocityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVelocityRequest.ProtoReflect.Descriptor instead.
func (*ApplyVelocityRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyVelocityRequest) GetTwist() *Twist {
	if x != nil {
		return x.Twist
	}
	return nil
}

func (x *ApplyVelocityRequest) GetDeadlineUnixMs() uint64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *ApplyVelocityRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ApplyVelocityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Motion        *MotionState           `protobuf:"bytes,1,opt,name=motion,proto3" json:"motion,omitempty"`
	Status        *HardwareStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyVelocityResponse) Reset() {
	*x = ApplyVelocityResponse{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVelocityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVelocityResponse) ProtoMessage() {}

func (x *ApplyVelocityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVelocityResponse.ProtoReflect.Descriptor instead.
func (*ApplyVelocityResponse) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyVelocityResponse) GetMotion() *MotionState {
	if x != nil {
		return x.Motion
	}
	return nil
}

func (x *ApplyVelocityResponse) GetStatus() *HardwareStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{7}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Motion        *MotionState           `protobuf:"bytes,1,opt,name=motion,proto3" json:"motion,omitempty"`
	Status        *HardwareStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP(), []int{8}
}

func (x *StopResponse) GetMotion() *MotionState {
	if x != nil {
		return x.Motion
	}
	return nil
}

func (x *StopResponse) GetStatus() *HardwareStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_txing_unit_hardware_v1_unit_hardware_proto protoreflect.FileDescriptor

const file_txing_unit_hardware_v1_unit_hardware_proto_rawDesc = "" +
	"\n" +
	"*txing/unit/hardware/v1/unit_hardware.proto\x12\x16txing.unit.hardware.v1\"\x12\n" +
	"\x10GetStatusRequest\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"{\n" +
	"\x05Twist\x127\n" +
	"\x06linear\x18\x01 \x01(\v2\x1f.txing.unit.hardware.v1.Vector3R\x06linear\x129\n" +
	"\aangular\x18\x02 \x01(\v2\x1f.txing.unit.hardware.v1.Vector3R\aangular\"i\n" +
	"\vMotionState\x12\x1d\n" +
	"\n" +
	"left_speed\x18\x01 \x01(\x05R\tleftSpeed\x12\x1f\n" +
	"\vright_speed\x18\x02 \x01(\x05R\n" +
	"rightSpeed\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\xcf\x02\n" +
	"\x0eHardwareStatus\x12;\n" +
	"\x05state\x18\x01 \x01(\x0e2%.txing.unit.hardware.v1.HardwareStateR\x05state\x12%\n" +
	"\x0eactuator_ready\x18\x02 \x01(\bR\ractuatorReady\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\x12;\n" +
	"\x06motion\x18\x04 \x01(\v2#.txing.unit.hardware.v1.MotionStateR\x06motion\x12:\n" +
	"\x17active_deadline_unix_ms\x18\x05 \x01(\x04H\x00R\x14activeDeadlineUnixMs\x88\x01\x01\x12%\n" +
	"\x0eworker_version\x18\x06 \x01(\tR\rworkerVersionB\x1a\n" +
	"\x18_active_deadline_unix_ms\"\x94\x01\n" +
	"\x14ApplyVelocityRequest\x123\n" +
	"\x05twist\x18\x01 \x01(\v2\x1d.txing.unit.hardware.v1.TwistR\x05twist\x12(\n" +
	"\x10deadline_unix_ms\x18\x02 \x01(\x04R\x0edeadlineUnixMs\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"\x94\x01\n" +
	"\x15ApplyVelocityResponse\x12;\n" +
	"\x06motion\x18\x01 \x01(\v2#.txing.unit.hardware.v1.MotionStateR\x06motion\x12>\n" +
	"\x06status\x18\x02 \x01(\v2&.txing.unit.hardware.v1.HardwareStatusR\x06status\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x8b\x01\n" +
	"\fStopResponse\x12;\n" +
	"\x06motion\x18\x01 \x01(\v2#.txing.unit.hardware.v1.MotionStateR\x06motion\x12>\n" +
	"\x06status\x18\x02 \x01(\v2&.txing.unit.hardware.v1.HardwareStatusR\x06status*n\n" +
	"\rHardwareState\x12\x1e\n" +
	"\x1aHARDWARE_STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\f\n" +
	"\bDEGRADED\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\v\n" +
	"\aSTOPPED\x10\x052\xae\x02\n" +
	"\fUnitHardware\x12]\n" +
	"\tGetStatus\x12(.txing.unit.hardware.v1.GetStatusRequest\x1a&.txing.unit.hardware.v1.HardwareStatus\x12l\n" +
	"\rApplyVelocity\x12,.txing.unit.hardware.v1.ApplyVelocityRequest\x1a-.txing.unit.hardware.v1.ApplyVelocityResponse\x12Q\n" +
	"\x04Stop\x12#.txing.unit.hardware.v1.StopRequest\x1a$.txing.unit.hardware.v1.StopResponseb\x06proto3"

var (
	file_txing_unit_hardware_v1_unit_hardware_proto_rawDescOnce sync.Once
	file_txing_unit_hardware_v1_unit_hardware_proto_rawDescData []byte
)

func file_txing_unit_hardware_v1_unit_hardware_proto_rawDescGZIP() []byte {
	file_txing_unit_hardware_v1_unit_hardware_proto_rawDescOnce.Do(func() {
		file_txing_unit_hardware_v1_unit_hardware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txing_unit_hardware_v1_unit_hardware_proto_rawDesc), len(file_txing_unit_hardware_v1_unit_hardware_proto_rawDesc)))
	})
	return file_txing_unit_hardware_v1_unit_hardware_proto_rawDescData
}

var file_txing_unit_hardware_v1_unit_hardware_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_txing_unit_hardware_v1_unit_hardware_proto_goTypes = []any{
	(HardwareState)(0),            // 0: txing.unit.hardware.v1.HardwareState
	(*GetStatusRequest)(nil),      // 1: txing.unit.hardware.v1.GetStatusRequest
	(*Vector3)(nil),               // 2: txing.unit.hardware.v1.Vector3
	(*Twist)(nil),                 // 3: txing.unit.hardware.v1.Twist
	(*MotionState)(nil),           // 4: txing.unit.hardware.v1.MotionState
	(*HardwareStatus)(nil),        // 5: txing.unit.hardware.v1.HardwareStatus
	(*ApplyVelocityRequest)(nil),  // 6: txing.unit.hardware.v1.ApplyVelocityRequest
	(*ApplyVelocityResponse)(nil), // 7: txing.unit.hardware.v1.ApplyVelocityResponse
	(*StopRequest)(nil),           // 8: txing.unit.hardware.v1.StopRequest
	(*StopResponse)(nil),          // 9: txing.unit.hardware.v1.StopResponse
}
var file_txing_unit_hardware_v1_unit_hardware_proto_depIdxs = []int32{
	2,  // 0: txing.unit.hardware.v1.Twist.linear:type_name -> txing.unit.hardware.v1.Vector3
	2,  // 1: txing.unit.hardware.v1.Twist.angular:type_name -> txing.unit.hardware.v1.Vector3
	0,  // 2: txing.unit.hardware.v1.HardwareStatus.state:type_name -> txing.unit.hardware.v1.HardwareState
	4,  // 3: txing.unit.hardware.v1.HardwareStatus.motion:type_name -> txing.unit.hardware.v1.MotionState
	3,  // 4: txing.unit.hardware.v1.ApplyVelocityRequest.twist:type_name -> txing.unit.hardware.v1.Twist
	4,  // 5: txing.unit.hardware.v1.ApplyVelocityResponse.motion:type_name -> txing.unit.hardware.v1.MotionState
	5,  // 6: txing.unit.hardware.v1.ApplyVelocityResponse.status:type_name -> txing.unit.hardware.v1.HardwareStatus
	4,  // 7: txing.unit.hardware.v1.StopResponse.motion:type_name -> txing.unit.hardware.v1.MotionState
	5,  // 8: txing.unit.hardware.v1.StopResponse.status:type_name -> txing.unit.hardware.v1.HardwareStatus
	1,  // 9: txing.unit.hardware.v1.UnitHardware.GetStatus:input_type -> txing.unit.hardware.v1.GetStatusRequest
	6,  // 10: txing.unit.hardware.v1.UnitHardware.ApplyVelocity:input_type -> txing.unit.hardware.v1.ApplyVelocityRequest
	8,  // 11: txing.unit.hardware.v1.UnitHardware.Stop:input_type -> txing.unit.hardware.v1.StopRequest
	5,  // 12: txing.unit.hardware.v1.UnitHardware.GetStatus:output_type -> txing.unit.hardware.v1.HardwareStatus
	7,  // 13: txing.unit.hardware.v1.UnitHardware.ApplyVelocity:output_type -> txing.unit.hardware.v1.ApplyVelocityResponse
	9,  // 14: txing.unit.hardware.v1.UnitHardware.Stop:output_type -> txing.unit.hardware.v1.StopResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_txing_unit_hardware_v1_unit_hardware_proto_init() }
func file_txing_unit_hardware_v1_unit_hardware_proto_init() {
	if File_txing_unit_hardware_v1_unit_hardware_proto != nil {
		return
	}
	file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txing_unit_hardware_v1_unit_hardware_proto_rawDesc), len(file_txing_unit_hardware_v1_unit_hardware_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txing_unit_hardware_v1_unit_hardware_proto_goTypes,
		DependencyIndexes: file_txing_unit_hardware_v1_unit_hardware_proto_depIdxs,
		EnumInfos:         file_txing_unit_hardware_v1_unit_hardware_proto_enumTypes,
		MessageInfos:      file_txing_unit_hardware_v1_unit_hardware_proto_msgTypes,
	}.Build()
	File_txing_unit_hardware_v1_unit_hardware_proto = out.File
	file_txing_unit_hardware_v1_unit_hardware_proto_goTypes = nil
	file_txing_unit_hardware_v1_unit_hardware_proto_depIdxs = nil
}
