set shell := ["sh", "-eu", "-c"]
set quiet := true

common_dir := source_directory()
project_root := canonicalize(common_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir

@default:
    @just --list
