set shell := ["sh", "-eu", "-c"]
set quiet := true

power_si_dir := source_directory()
project_root := canonicalize(power_si_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir

mod mcu 'mcu/justfile'

@default:
    @just --list
