set shell := ["sh", "-eu", "-c"]
set quiet := true

tbot_dir := source_directory()
project_root := canonicalize(tbot_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir

mod mcu 'mcu/justfile'

mod board 'board.just'

@default:
    @just --list
