set shell := ["bash", "-eu", "-o", "pipefail", "-c"]
set quiet := true

witness_dir := source_directory()

@test:
    cargo test --manifest-path "{{witness_dir}}/Cargo.toml"

build:
    cd "{{witness_dir}}" && cargo lambda build --release

deploy: build
    cd "{{witness_dir}}" && cargo lambda deploy

@default:
    @just --list
