set shell := ["sh", "-eu", "-c"]
set quiet := true

lambda_dir := source_directory()
project_root := canonicalize(lambda_dir + "/../../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir
root_justfile := project_root + "/justfile"
aws_lib := project_root + "/shared/aws/scripts/aws_lib.sh"
cloud_rig_template := lambda_dir + "/cmd/txing-cloud-rig-lambda/template.yaml"
cloud_mcu_template := lambda_dir + "/cmd/txing-cloud-mcu-lambda/template.yaml"

stack_name := ""

@test:
    cd "{{lambda_dir}}" && go test -tags lambda.norpc ./...

deploy stack_name=stack_name:
    just --justfile "{{lambda_dir}}/justfile" deploy-cloud-mcu "{{stack_name}}"
    just --justfile "{{lambda_dir}}/justfile" deploy-cloud-rig "{{stack_name}}"

deploy-cloud-rig stack_name=stack_name:
    #!/bin/sh
    set -eu
    cd "{{lambda_dir}}"
    . "{{aws_lib}}"
    eval "$(just --justfile "{{root_justfile}}" _project-aws-env aws "{{stack_name}}")"
    txing_aws_init
    artifact_bucket="$(ensure_artifact_bucket)"
    ensure_lambda_seed_artifact txing-cloud-rig-lambda "$artifact_bucket"
    deploy_template "$(lambda_stack_name cloud-rig)" "{{cloud_rig_template}}" \
      "EnvironmentStackName=$TXING_AWS_STACK"

deploy-cloud-mcu stack_name=stack_name:
    #!/bin/sh
    set -eu
    cd "{{lambda_dir}}"
    . "{{aws_lib}}"
    eval "$(just --justfile "{{root_justfile}}" _project-aws-env aws "{{stack_name}}")"
    txing_aws_init
    artifact_bucket="$(ensure_artifact_bucket)"
    ensure_lambda_seed_artifact txing-cloud-mcu-lambda "$artifact_bucket"
    deploy_template "$(lambda_stack_name cloud-mcu)" "{{cloud_mcu_template}}" \
      "EnvironmentStackName=$TXING_AWS_STACK"

@default:
    @just --list
