[platformio]
core_dir = .platformio-core
build_dir = .pio/build

[env:seeed-xiao-nrf54l15]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54l15
build_type = release
monitor_speed = 115200
