set shell := ["sh", "-eu", "-c"]
set quiet := true

unit_dir := source_directory()
project_root := canonicalize(unit_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir
mod mcu 'mcu/justfile'

mod board 'board.just'

@default:
    @just --list
