set shell := ["sh", "-eu", "-c"]
set quiet := true

cyberbrick_dir := source_directory()
project_root := canonicalize(cyberbrick_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir

mod daemon 'daemon/justfile'

@default:
    @just --list
