set shell := ["sh", "-eu", "-c"]
set quiet := true

cyberbrick_dir := source_directory()
project_root := canonicalize(cyberbrick_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir


mod board 'board.just'
mod ardupilot 'ardupilot.just'
mod mavlink 'mavlink.just'

@default:
    @just --list
