[target.thumbv7em-none-eabihf]
rustflags = [ "-C", "link-arg=-Tlink.x" ]

[build]
target = "thumbv7em-none-eabihf"

[alias]
# Runs the local xtask utility on the host toolchain.
# If your host is not Apple Silicon macOS, replace the target triple below.
fw = "run --manifest-path xtask/Cargo.toml --target aarch64-apple-darwin --"
