CONFIG_GPIO=y
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SHELL_BACKEND_SERIAL=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n

CONFIG_PM_DEVICE=y
CONFIG_NRFX_POWER=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_FIXED=y
CONFIG_CRC=y

CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="txing-unconfigured"
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_DEVICE_NAME_MAX=26
CONFIG_BT_BROADCASTER=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_ATT_PREPARE_COUNT=1
CONFIG_BT_LL_SW_SPLIT=y

CONFIG_ADC=y

CONFIG_REDCON_BATTERY_ADC_SETTLE_MS=100
CONFIG_REDCON_FACTORY_DATA_ADDRESS=0x000f0000
CONFIG_REDCON_COMMAND_LEVELS_MASK=0x18
CONFIG_REDCON_PRESERVE_LEVEL_ON_DISCONNECT=y
CONFIG_REDCON_BLE_ADV_INTERVAL=0x0800
CONFIG_REDCON_BLE_ADV_TX_POWER_DBM=4
CONFIG_REDCON_BLE_CONN_INTERVAL_MS=100
CONFIG_REDCON_BLE_CONN_LATENCY=0
CONFIG_REDCON_BLE_CONN_SUPERVISION_MS=20000
CONFIG_REDCON_BLE_MEASUREMENT_NOTIFY_INTERVAL_SECONDS=10
CONFIG_REDCON_BLE_IDLE_MEASUREMENT_NOTIFY_INTERVAL_SECONDS=60
