// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: txing/unit/board_video/v1/board_video.proto

package boardvideov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoardVideoBridge_GetWorkerConfig_FullMethodName    = "/txing.unit.board_video.v1.BoardVideoBridge/GetWorkerConfig"
	BoardVideoBridge_RefreshCredentials_FullMethodName = "/txing.unit.board_video.v1.BoardVideoBridge/RefreshCredentials"
	BoardVideoBridge_ReportVideoState_FullMethodName   = "/txing.unit.board_video.v1.BoardVideoBridge/ReportVideoState"
	BoardVideoBridge_OpenMcpSession_FullMethodName     = "/txing.unit.board_video.v1.BoardVideoBridge/OpenMcpSession"
	BoardVideoBridge_HandleMcp_FullMethodName          = "/txing.unit.board_video.v1.BoardVideoBridge/HandleMcp"
	BoardVideoBridge_CloseMcpSession_FullMethodName    = "/txing.unit.board_video.v1.BoardVideoBridge/CloseMcpSession"
)

// BoardVideoBridgeClient is the client API for BoardVideoBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoardVideoBridgeClient interface {
	GetWorkerConfig(ctx context.Context, in *WorkerHello, opts ...grpc.CallOption) (*WorkerConfig, error)
	RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*KvsCredentials, error)
	ReportVideoState(ctx context.Context, in *VideoState, opts ...grpc.CallOption) (*Ack, error)
	OpenMcpSession(ctx context.Context, in *OpenMcpSessionRequest, opts ...grpc.CallOption) (*Ack, error)
	HandleMcp(ctx context.Context, in *McpRequest, opts ...grpc.CallOption) (*McpResponse, error)
	CloseMcpSession(ctx context.Context, in *CloseMcpSessionRequest, opts ...grpc.CallOption) (*Ack, error)
}

type boardVideoBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBoardVideoBridgeClient(cc grpc.ClientConnInterface) BoardVideoBridgeClient {
	return &boardVideoBridgeClient{cc}
}

func (c *boardVideoBridgeClient) GetWorkerConfig(ctx context.Context, in *WorkerHello, opts ...grpc.CallOption) (*WorkerConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerConfig)
	err := c.cc.Invoke(ctx, BoardVideoBridge_GetWorkerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardVideoBridgeClient) RefreshCredentials(ctx context.Context, in *RefreshCredentialsRequest, opts ...grpc.CallOption) (*KvsCredentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvsCredentials)
	err := c.cc.Invoke(ctx, BoardVideoBridge_RefreshCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardVideoBridgeClient) ReportVideoState(ctx context.Context, in *VideoState, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, BoardVideoBridge_ReportVideoState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardVideoBridgeClient) OpenMcpSession(ctx context.Context, in *OpenMcpSessionRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, BoardVideoBridge_OpenMcpSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardVideoBridgeClient) HandleMcp(ctx context.Context, in *McpRequest, opts ...grpc.CallOption) (*McpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpResponse)
	err := c.cc.Invoke(ctx, BoardVideoBridge_HandleMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardVideoBridgeClient) CloseMcpSession(ctx context.Context, in *CloseMcpSessionRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, BoardVideoBridge_CloseMcpSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardVideoBridgeServer is the server API for BoardVideoBridge service.
// All implementations must embed UnimplementedBoardVideoBridgeServer
// for forward compatibility.
type BoardVideoBridgeServer interface {
	GetWorkerConfig(context.Context, *WorkerHello) (*WorkerConfig, error)
	RefreshCredentials(context.Context, *RefreshCredentialsRequest) (*KvsCredentials, error)
	ReportVideoState(context.Context, *VideoState) (*Ack, error)
	OpenMcpSession(context.Context, *OpenMcpSessionRequest) (*Ack, error)
	HandleMcp(context.Context, *McpRequest) (*McpResponse, error)
	CloseMcpSession(context.Context, *CloseMcpSessionRequest) (*Ack, error)
	mustEmbedUnimplementedBoardVideoBridgeServer()
}

// UnimplementedBoardVideoBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoardVideoBridgeServer struct{}

func (UnimplementedBoardVideoBridgeServer) GetWorkerConfig(context.Context, *WorkerHello) (*WorkerConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerConfig not implemented")
}
func (UnimplementedBoardVideoBridgeServer) RefreshCredentials(context.Context, *RefreshCredentialsRequest) (*KvsCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshCredentials not implemented")
}
func (UnimplementedBoardVideoBridgeServer) ReportVideoState(context.Context, *VideoState) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportVideoState not implemented")
}
func (UnimplementedBoardVideoBridgeServer) OpenMcpSession(context.Context, *OpenMcpSessionRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenMcpSession not implemented")
}
func (UnimplementedBoardVideoBridgeServer) HandleMcp(context.Context, *McpRequest) (*McpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleMcp not implemented")
}
func (UnimplementedBoardVideoBridgeServer) CloseMcpSession(context.Context, *CloseMcpSessionRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseMcpSession not implemented")
}
func (UnimplementedBoardVideoBridgeServer) mustEmbedUnimplementedBoardVideoBridgeServer() {}
func (UnimplementedBoardVideoBridgeServer) testEmbeddedByValue()                          {}

// UnsafeBoardVideoBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoardVideoBridgeServer will
// result in compilation errors.
type UnsafeBoardVideoBridgeServer interface {
	mustEmbedUnimplementedBoardVideoBridgeServer()
}

func RegisterBoardVideoBridgeServer(s grpc.ServiceRegistrar, srv BoardVideoBridgeServer) {
	// If the following call pancis, it indicates UnimplementedBoardVideoBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoardVideoBridge_ServiceDesc, srv)
}

func _BoardVideoBridge_GetWorkerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).GetWorkerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_GetWorkerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).GetWorkerConfig(ctx, req.(*WorkerHello))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardVideoBridge_RefreshCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).RefreshCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_RefreshCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).RefreshCredentials(ctx, req.(*RefreshCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardVideoBridge_ReportVideoState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).ReportVideoState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_ReportVideoState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).ReportVideoState(ctx, req.(*VideoState))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardVideoBridge_OpenMcpSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenMcpSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).OpenMcpSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_OpenMcpSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).OpenMcpSession(ctx, req.(*OpenMcpSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardVideoBridge_HandleMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).HandleMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_HandleMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).HandleMcp(ctx, req.(*McpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardVideoBridge_CloseMcpSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseMcpSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardVideoBridgeServer).CloseMcpSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardVideoBridge_CloseMcpSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardVideoBridgeServer).CloseMcpSession(ctx, req.(*CloseMcpSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoardVideoBridge_ServiceDesc is the grpc.ServiceDesc for BoardVideoBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoardVideoBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "txing.unit.board_video.v1.BoardVideoBridge",
	HandlerType: (*BoardVideoBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkerConfig",
			Handler:    _BoardVideoBridge_GetWorkerConfig_Handler,
		},
		{
			MethodName: "RefreshCredentials",
			Handler:    _BoardVideoBridge_RefreshCredentials_Handler,
		},
		{
			MethodName: "ReportVideoState",
			Handler:    _BoardVideoBridge_ReportVideoState_Handler,
		},
		{
			MethodName: "OpenMcpSession",
			Handler:    _BoardVideoBridge_OpenMcpSession_Handler,
		},
		{
			MethodName: "HandleMcp",
			Handler:    _BoardVideoBridge_HandleMcp_Handler,
		},
		{
			MethodName: "CloseMcpSession",
			Handler:    _BoardVideoBridge_CloseMcpSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txing/unit/board_video/v1/board_video.proto",
}
