set shell := ["sh", "-eu", "-c"]
set quiet := true

lambda_dir := source_directory()
aws_dir := canonicalize(lambda_dir + "/../..")
project_root := canonicalize(aws_dir + "/../..")
tmp_dir := project_root + "/tmp"
export TMPDIR := tmp_dir
root_justfile := project_root + "/justfile"
aws_lib := aws_dir + "/scripts/aws_lib.sh"

stack_name := ""

deploy stack_name=stack_name:
    #!/bin/sh
    set -eu
    cd "{{aws_dir}}"
    . "{{aws_lib}}"
    eval "$(just --justfile "{{root_justfile}}" _project-aws-env aws "{{stack_name}}")"
    txing_aws_init
    artifact_bucket="$(ensure_artifact_bucket)"
    deploy_template "$(lambda_stack_name aws-publish-release)" "{{lambda_dir}}/template.yaml" \
      "EnvironmentStackName=$TXING_AWS_STACK" \
      "LambdaArtifactsBucketName=$artifact_bucket"

@default:
    @just --list
