// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: txing/unit/board_video/v1/board_video.proto

package boardvideov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoState_State int32

const (
	VideoState_STATE_UNSPECIFIED VideoState_State = 0
	VideoState_STARTING          VideoState_State = 1
	VideoState_READY             VideoState_State = 2
	VideoState_ERROR             VideoState_State = 3
)

// Enum value maps for VideoState_State.
var (
	VideoState_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STARTING",
		2: "READY",
		3: "ERROR",
	}
	VideoState_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STARTING":          1,
		"READY":             2,
		"ERROR":             3,
	}
)

func (x VideoState_State) Enum() *VideoState_State {
	p := new(VideoState_State)
	*p = x
	return p
}

func (x VideoState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_txing_unit_board_video_v1_board_video_proto_enumTypes[0].Descriptor()
}

func (VideoState_State) Type() protoreflect.EnumType {
	return &file_txing_unit_board_video_v1_board_video_proto_enumTypes[0]
}

func (x VideoState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoState_State.Descriptor instead.
func (VideoState_State) EnumDescriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{5, 0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{0}
}

type WorkerHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	WorkerName      string                 `protobuf:"bytes,2,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	WorkerVersion   string                 `protobuf:"bytes,3,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *WorkerHello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *WorkerHello) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

type WorkerConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Region               string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	ChannelName          string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ClientId             string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	McpDataChannelLabel  string                 `protobuf:"bytes,4,opt,name=mcp_data_channel_label,json=mcpDataChannelLabel,proto3" json:"mcp_data_channel_label,omitempty"`
	McpResponseTimeoutMs uint32                 `protobuf:"varint,5,opt,name=mcp_response_timeout_ms,json=mcpResponseTimeoutMs,proto3" json:"mcp_response_timeout_ms,omitempty"`
	PreferIpv6           bool                   `protobuf:"varint,6,opt,name=prefer_ipv6,json=preferIpv6,proto3" json:"prefer_ipv6,omitempty"`
	DisableIpv4Turn      bool                   `protobuf:"varint,7,opt,name=disable_ipv4_turn,json=disableIpv4Turn,proto3" json:"disable_ipv4_turn,omitempty"`
	Credentials          *KvsCredentials        `protobuf:"bytes,8,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkerConfig) Reset() {
	*x = WorkerConfig{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerConfig) ProtoMessage() {}

func (x *WorkerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerConfig.ProtoReflect.Descriptor instead.
func (*WorkerConfig) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *WorkerConfig) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *WorkerConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WorkerConfig) GetMcpDataChannelLabel() string {
	if x != nil {
		return x.McpDataChannelLabel
	}
	return ""
}

func (x *WorkerConfig) GetMcpResponseTimeoutMs() uint32 {
	if x != nil {
		return x.McpResponseTimeoutMs
	}
	return 0
}

func (x *WorkerConfig) GetPreferIpv6() bool {
	if x != nil {
		return x.PreferIpv6
	}
	return false
}

func (x *WorkerConfig) GetDisableIpv4Turn() bool {
	if x != nil {
		return x.DisableIpv4Turn
	}
	return false
}

func (x *WorkerConfig) GetCredentials() *KvsCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RefreshCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCredentialsRequest) Reset() {
	*x = RefreshCredentialsRequest{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCredentialsRequest) ProtoMessage() {}

func (x *RefreshCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCredentialsRequest.ProtoReflect.Descriptor instead.
func (*RefreshCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{3}
}

type KvsCredentials struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KvsCredentials) Reset() {
	*x = KvsCredentials{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvsCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvsCredentials) ProtoMessage() {}

func (x *KvsCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvsCredentials.ProtoReflect.Descriptor instead.
func (*KvsCredentials) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{4}
}

func (x *KvsCredentials) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *KvsCredentials) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *KvsCredentials) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *KvsCredentials) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VideoState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         VideoState_State       `protobuf:"varint,1,opt,name=state,proto3,enum=txing.unit.board_video.v1.VideoState_State" json:"state,omitempty"`
	ViewerCount   uint32                 `protobuf:"varint,2,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoState) Reset() {
	*x = VideoState{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoState) ProtoMessage() {}

func (x *VideoState) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoState.ProtoReflect.Descriptor instead.
func (*VideoState) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{5}
}

func (x *VideoState) GetState() VideoState_State {
	if x != nil {
		return x.State
	}
	return VideoState_STATE_UNSPECIFIED
}

func (x *VideoState) GetViewerCount() uint32 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *VideoState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OpenMcpSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpSessionId  string                 `protobuf:"bytes,1,opt,name=mcp_session_id,json=mcpSessionId,proto3" json:"mcp_session_id,omitempty"`
	Transport     string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenMcpSessionRequest) Reset() {
	*x = OpenMcpSessionRequest{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenMcpSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenMcpSessionRequest) ProtoMessage() {}

func (x *OpenMcpSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenMcpSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenMcpSessionRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{6}
}

func (x *OpenMcpSessionRequest) GetMcpSessionId() string {
	if x != nil {
		return x.McpSessionId
	}
	return ""
}

func (x *OpenMcpSessionRequest) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *OpenMcpSessionRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type McpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpSessionId  string                 `protobuf:"bytes,1,opt,name=mcp_session_id,json=mcpSessionId,proto3" json:"mcp_session_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpRequest) Reset() {
	*x = McpRequest{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpRequest) ProtoMessage() {}

func (x *McpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpRequest.ProtoReflect.Descriptor instead.
func (*McpRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{7}
}

func (x *McpRequest) GetMcpSessionId() string {
	if x != nil {
		return x.McpSessionId
	}
	return ""
}

func (x *McpRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type McpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPayload    bool                   `protobuf:"varint,1,opt,name=has_payload,json=hasPayload,proto3" json:"has_payload,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpResponse) Reset() {
	*x = McpResponse{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpResponse) ProtoMessage() {}

func (x *McpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpResponse.ProtoReflect.Descriptor instead.
func (*McpResponse) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{8}
}

func (x *McpResponse) GetHasPayload() bool {
	if x != nil {
		return x.HasPayload
	}
	return false
}

func (x *McpResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CloseMcpSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpSessionId  string                 `protobuf:"bytes,1,opt,name=mcp_session_id,json=mcpSessionId,proto3" json:"mcp_session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseMcpSessionRequest) Reset() {
	*x = CloseMcpSessionRequest{}
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseMcpSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseMcpSessionRequest) ProtoMessage() {}

func (x *CloseMcpSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_txing_unit_board_video_v1_board_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseMcpSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseMcpSessionRequest) Descriptor() ([]byte, []int) {
	return file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP(), []int{9}
}

func (x *CloseMcpSessionRequest) GetMcpSessionId() string {
	if x != nil {
		return x.McpSessionId
	}
	return ""
}

func (x *CloseMcpSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_txing_unit_board_video_v1_board_video_proto protoreflect.FileDescriptor

const file_txing_unit_board_video_v1_board_video_proto_rawDesc = "" +
	"\n" +
	"+txing/unit/board_video/v1/board_video.proto\x12\x19txing.unit.board_video.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x05\n" +
	"\x03Ack\"\x80\x01\n" +
	"\vWorkerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vworker_name\x18\x02 \x01(\tR\n" +
	"workerName\x12%\n" +
	"\x0eworker_version\x18\x03 \x01(\tR\rworkerVersion\"\xec\x02\n" +
	"\fWorkerConfig\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x123\n" +
	"\x16mcp_data_channel_label\x18\x04 \x01(\tR\x13mcpDataChannelLabel\x125\n" +
	"\x17mcp_response_timeout_ms\x18\x05 \x01(\rR\x14mcpResponseTimeoutMs\x12\x1f\n" +
	"\vprefer_ipv6\x18\x06 \x01(\bR\n" +
	"preferIpv6\x12*\n" +
	"\x11disable_ipv4_turn\x18\a \x01(\bR\x0fdisableIpv4Turn\x12K\n" +
	"\vcredentials\x18\b \x01(\v2).txing.unit.board_video.v1.KvsCredentialsR\vcredentials\"\x1b\n" +
	"\x19RefreshCredentialsRequest\"\xc0\x01\n" +
	"\x0eKvsCredentials\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xcc\x01\n" +
	"\n" +
	"VideoState\x12A\n" +
	"\x05state\x18\x01 \x01(\x0e2+.txing.unit.board_video.v1.VideoState.StateR\x05state\x12!\n" +
	"\fviewer_count\x18\x02 \x01(\rR\vviewerCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"t\n" +
	"\x15OpenMcpSessionRequest\x12$\n" +
	"\x0emcp_session_id\x18\x01 \x01(\tR\fmcpSessionId\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\"L\n" +
	"\n" +
	"McpRequest\x12$\n" +
	"\x0emcp_session_id\x18\x01 \x01(\tR\fmcpSessionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"H\n" +
	"\vMcpResponse\x12\x1f\n" +
	"\vhas_payload\x18\x01 \x01(\bR\n" +
	"hasPayload\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"V\n" +
	"\x16CloseMcpSessionRequest\x12$\n" +
	"\x0emcp_session_id\x18\x01 \x01(\tR\fmcpSessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xee\x04\n" +
	"\x10BoardVideoBridge\x12b\n" +
	"\x0fGetWorkerConfig\x12&.txing.unit.board_video.v1.WorkerHello\x1a'.txing.unit.board_video.v1.WorkerConfig\x12u\n" +
	"\x12RefreshCredentials\x124.txing.unit.board_video.v1.RefreshCredentialsRequest\x1a).txing.unit.board_video.v1.KvsCredentials\x12Y\n" +
	"\x10ReportVideoState\x12%.txing.unit.board_video.v1.VideoState\x1a\x1e.txing.unit.board_video.v1.Ack\x12b\n" +
	"\x0eOpenMcpSession\x120.txing.unit.board_video.v1.OpenMcpSessionRequest\x1a\x1e.txing.unit.board_video.v1.Ack\x12Z\n" +
	"\tHandleMcp\x12%.txing.unit.board_video.v1.McpRequest\x1a&.txing.unit.board_video.v1.McpResponse\x12d\n" +
	"\x0fCloseMcpSession\x121.txing.unit.board_video.v1.CloseMcpSessionRequest\x1a\x1e.txing.unit.board_video.v1.Ackb\x06proto3"

var (
	file_txing_unit_board_video_v1_board_video_proto_rawDescOnce sync.Once
	file_txing_unit_board_video_v1_board_video_proto_rawDescData []byte
)

func file_txing_unit_board_video_v1_board_video_proto_rawDescGZIP() []byte {
	file_txing_unit_board_video_v1_board_video_proto_rawDescOnce.Do(func() {
		file_txing_unit_board_video_v1_board_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txing_unit_board_video_v1_board_video_proto_rawDesc), len(file_txing_unit_board_video_v1_board_video_proto_rawDesc)))
	})
	return file_txing_unit_board_video_v1_board_video_proto_rawDescData
}

var file_txing_unit_board_video_v1_board_video_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txing_unit_board_video_v1_board_video_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_txing_unit_board_video_v1_board_video_proto_goTypes = []any{
	(VideoState_State)(0),             // 0: txing.unit.board_video.v1.VideoState.State
	(*Ack)(nil),                       // 1: txing.unit.board_video.v1.Ack
	(*WorkerHello)(nil),               // 2: txing.unit.board_video.v1.WorkerHello
	(*WorkerConfig)(nil),              // 3: txing.unit.board_video.v1.WorkerConfig
	(*RefreshCredentialsRequest)(nil), // 4: txing.unit.board_video.v1.RefreshCredentialsRequest
	(*KvsCredentials)(nil),            // 5: txing.unit.board_video.v1.KvsCredentials
	(*VideoState)(nil),                // 6: txing.unit.board_video.v1.VideoState
	(*OpenMcpSessionRequest)(nil),     // 7: txing.unit.board_video.v1.OpenMcpSessionRequest
	(*McpRequest)(nil),                // 8: txing.unit.board_video.v1.McpRequest
	(*McpResponse)(nil),               // 9: txing.unit.board_video.v1.McpResponse
	(*CloseMcpSessionRequest)(nil),    // 10: txing.unit.board_video.v1.CloseMcpSessionRequest
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_txing_unit_board_video_v1_board_video_proto_depIdxs = []int32{
	5,  // 0: txing.unit.board_video.v1.WorkerConfig.credentials:type_name -> txing.unit.board_video.v1.KvsCredentials
	11, // 1: txing.unit.board_video.v1.KvsCredentials.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: txing.unit.board_video.v1.VideoState.state:type_name -> txing.unit.board_video.v1.VideoState.State
	2,  // 3: txing.unit.board_video.v1.BoardVideoBridge.GetWorkerConfig:input_type -> txing.unit.board_video.v1.WorkerHello
	4,  // 4: txing.unit.board_video.v1.BoardVideoBridge.RefreshCredentials:input_type -> txing.unit.board_video.v1.RefreshCredentialsRequest
	6,  // 5: txing.unit.board_video.v1.BoardVideoBridge.ReportVideoState:input_type -> txing.unit.board_video.v1.VideoState
	7,  // 6: txing.unit.board_video.v1.BoardVideoBridge.OpenMcpSession:input_type -> txing.unit.board_video.v1.OpenMcpSessionRequest
	8,  // 7: txing.unit.board_video.v1.BoardVideoBridge.HandleMcp:input_type -> txing.unit.board_video.v1.McpRequest
	10, // 8: txing.unit.board_video.v1.BoardVideoBridge.CloseMcpSession:input_type -> txing.unit.board_video.v1.CloseMcpSessionRequest
	3,  // 9: txing.unit.board_video.v1.BoardVideoBridge.GetWorkerConfig:output_type -> txing.unit.board_video.v1.WorkerConfig
	5,  // 10: txing.unit.board_video.v1.BoardVideoBridge.RefreshCredentials:output_type -> txing.unit.board_video.v1.KvsCredentials
	1,  // 11: txing.unit.board_video.v1.BoardVideoBridge.ReportVideoState:output_type -> txing.unit.board_video.v1.Ack
	1,  // 12: txing.unit.board_video.v1.BoardVideoBridge.OpenMcpSession:output_type -> txing.unit.board_video.v1.Ack
	9,  // 13: txing.unit.board_video.v1.BoardVideoBridge.HandleMcp:output_type -> txing.unit.board_video.v1.McpResponse
	1,  // 14: txing.unit.board_video.v1.BoardVideoBridge.CloseMcpSession:output_type -> txing.unit.board_video.v1.Ack
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_txing_unit_board_video_v1_board_video_proto_init() }
func file_txing_unit_board_video_v1_board_video_proto_init() {
	if File_txing_unit_board_video_v1_board_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txing_unit_board_video_v1_board_video_proto_rawDesc), len(file_txing_unit_board_video_v1_board_video_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_txing_unit_board_video_v1_board_video_proto_goTypes,
		DependencyIndexes: file_txing_unit_board_video_v1_board_video_proto_depIdxs,
		EnumInfos:         file_txing_unit_board_video_v1_board_video_proto_enumTypes,
		MessageInfos:      file_txing_unit_board_video_v1_board_video_proto_msgTypes,
	}.Build()
	File_txing_unit_board_video_v1_board_video_proto = out.File
	file_txing_unit_board_video_v1_board_video_proto_goTypes = nil
	file_txing_unit_board_video_v1_board_video_proto_depIdxs = nil
}
